import { notFound } from "next/navigation";
import { getRequestConfig } from "next-intl/server";

// Define supported locales
export const locales = ['en', 'es'];
export const defaultLocale = 'en';

export default getRequestConfig(async ({ locale }: { locale: string }) => { // Generated by Copilot
    // Validate that the incoming 'locale' parameter is valid
    if (!locales.includes(locale)) notFound();

    return {
        messages: (await import(`../messages/${locale}.json`)).default
    };
});

export function isValidLocale(locale: string): boolean {
    return locales.includes(locale);
}